export type sortByParameters =
	| 'distance'
	| 'running_time'
	| 'average_cadence'
	| 'average_pace'
	| 'fastest_pace'
	| 'slowest_pace'
	| 'elevation_gain'
	| 'elevation_loss'
	| 'average_hr'
	| 'created_at'
	| 'updated_at'
